site_name: Array Engineering
site_url: https://arrayeng.org
site_description: Distributed Energy Resource consulting and software engineering in Seattle, WA.

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Roboto Mono
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress

extra_css:
  - https://fonts.googleapis.com/css2?family=Dosis:wght@400;600;700&display=swap
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adam-morse
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/adam-morse-pe

nav:
  - Home: index.md
  - Services: services.md
  - About: about.md
